version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/react'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99
    groups:
      react:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/vue'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99
    groups:
      vue:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/solid'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99
    groups:
      solid:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/svelte'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99
    groups:
      svelte:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/web'
    schedule:
      interval: weekly
      day: saturday
    open-pull-requests-limit: 99
    groups:
      web:
        patterns:
          - '*'
